Overwrite rerouting logic
maplibre/maplibre-navigation-ios pull request #16
Opened 2023-12-31 13:47 UTC by boldtrn

This changes makes it possible to write custom rerouting logic.

2024-01-03 14:44 UTC, mindthefish requested changes
Just some typos

2024-01-03 14:44 UTC, mindthefish commented on MapboxCoreNavigation/RouteControllerDelegate.swift
> +    If you want to overwrite the defult rerouting loigc, return true.
```suggestion
    If you want to overwrite the default rerouting logic, return true.
```

2024-01-03 14:44 UTC, mindthefish commented on MapboxCoreNavigation/RouteControllerDelegate.swift
> +     - parameter from: The current olocation of the user
```suggestion
     - parameter from: The current location of the user
```

2024-01-03 14:44 UTC, mindthefish commented on MapboxCoreNavigation/RouteControllerDelegate.swift
> +     - parameter completion: Callbackc function when either the route was sucessfully caluclated or if there was an error
```suggestion
     - parameter completion: Callback function when either the route was successfully calculated or if there was an error
```

2024-01-03 14:44 UTC, mindthefish commented on MapboxCoreNavigation/RouteControllerDelegate.swift
> +     - return: True to preferent the route controller from running its own rerouting logic
```suggestion
     - return: True to prevent the route controller from running its own rerouting logic
```

2024-01-03 15:13 UTC, boldtrn commented
Thanks, I just found the spellchecker in XCode, I will try my best to improve the spelling :)

2024-01-07 12:42 UTC, ianthetechie approved these changes
Sorry for the delay in reviewing this, but this looks good! Can't wait to try it out! Thanks @boldtrn!

2024-01-07 16:10 UTC, boldtrn commented
Thanks for the review @ianthetechie, I will go ahead and merge this PR.

2024-01-07 16:10 UTC, merged