Connect speech locale with route locale.
maplibre/maplibre-navigation-ios pull request #25
Opened 2024-02-05 13:02 UTC by StephanPartzsch

- Uses the `Locale` given in `RouteOptions` to create the correct `AVSpeechSynthesisVoice`.
- Extends the ui in the example with a button to specify the `Locale` for the `Route`.

2024-02-06 18:20 UTC, boldtrn requested changes
Thanks for looking into this. I think it makes a lot of sense to allow configuring the locale of the voice output. 

Would you mind adding a Changelog entry for your change so that implementers know what they need to do.

2024-02-07 15:47 UTC, boldtrn commented
Given the merge of #23, could you resolve the conflicts, then we can go ahead and merge this PR.

2024-02-08 06:06 UTC, StephanPartzsch commented on MapboxNavigation/RouteVoiceController.swift
>       - parameter instruction: The instruction to read aloud.
Good catch! 
Done

2024-02-08 08:57 UTC, boldtrn commented on Examples/Swift/Base.lproj/Main.storyboard
With the Maplibre 6.0 update, the storyboard needs to be changed from using `MBNavigationMapView` to `MLNavigationMapView`

2024-02-08 08:58 UTC, boldtrn requested changes
I just checked out your branch and tried to run it, it crashes due to the missing view in the storyboard, due to the update to Maplibre 6.

2024-02-08 15:06 UTC, StephanPartzsch commented on MapboxNavigation/RouteVoiceController.swift
> +            return
Done

2024-02-08 16:01 UTC, merged