Removing Mapbox Road Hardcoding
maplibre/maplibre-navigation-ios pull request #43
Opened 2024-05-18 17:35 UTC by hactar

During setting up, maplibre-navigation-ios checks if the mapbox street source is part of the map style. If it is not, it adds the source and creates a new layer. This results in the console throwing network errors as "mapbox://mapbox.mapbox-streets-v7" is not a valid URL in a non mapbox app.

This PR removes this hardcoded check - I guess this made sense when this was only used with mapbox services, but now that people use this with their non mapbox styles, this "hotfixing of the mapstyle" makes no sense.

2024-05-21 19:08 UTC, michaelkirk commented
I agree that it doesn't make sense to link to a mapbox url that the app doesn't even know how to handle.

Instead of removing this logic, is there a possibility of a maplibre hosted style?  In theory it seems kind of nice that things could "just work" for library users, but maybe the project isn't interested in the amount of hosting that would imply.

2024-05-23 00:43 UTC, michaelkirk commented
> Instead of removing this logic, is there a possibility of a maplibre hosted style?

I thought about this more while working on #45, and personally concluded that injecting default styles in the middle of the code base is probably not the right approach, so I take back my comment.

2024-05-23 00:45 UTC, michaelkirk commented on MapboxNavigation/RouteMapViewController.swift
> -        if streetsSources.isEmpty {
Do you expect that there are valid reasons for the person to be in this state where they would want to silently proceed without error?

If not, though we don't have a reasonable default layer to fall back to like mapbox did, could we instead help the user out with an assertionFailure or a log message here?

2024-05-24 16:14 UTC, boldtrn commented
Good catch to remove this code @hactar 👍. While I fully agree that we should remove this Mapbox specific logic here. There is similar usage here as well: https://github.com/maplibre/maplibre-navigation-ios/blob/3eda16937ca0f69f3ef42eb79c5de7f49919e918/MapboxNavigation/NavigationMapView.swift#L993

I am currently wondering if we should make this configurable or just completely remove?

2024-05-24 16:14 UTC, boldtrn requested changes
Thanks for working on this. Could you add a Changelog entry for this change?

2024-05-25 10:10 UTC, hactar commented
> Good catch to remove this code @hactar 👍. While I fully agree that we should remove this Mapbox specific logic here. There is similar usage here as well:
> 
> https://github.com/maplibre/maplibre-navigation-ios/blob/3eda16937ca0f69f3ef42eb79c5de7f49919e918/MapboxNavigation/NavigationMapView.swift#L993
> 
> I am currently wondering if we should make this configurable or just completely remove?

The one that I found should just be plain removed I think, but the one that you found is an interesting one - it tries to modify the street labels to the countries locale they are in so that they match the signs people might see on streets. That could be a useful feature, but we would need to change this so that we can provide maplibre navigation with the layers that contain the road networks, instead of it trying to find the "mapbox road network". And that layer also needs to support "mul" locale for this to work I guess... So that one should be investigated, but I suggest outside this ticket.

2024-05-25 10:10 UTC, hactar commented
> Thanks for working on this. Could you add a Changelog entry for this change?

Done.

2024-05-29 20:59 UTC, hactar commented
@boldtrn the conflict has been resolved, I have no write permissions so you or someone else will have to hit the button ☺️

2024-05-31 16:45 UTC, merged