Open RouteController to custom location snapping
maplibre/maplibre-navigation-ios pull request #85
Opened 2024-07-17 15:34 UTC by sotomski

### Description

This PR opens the `RouteController.snappedLocation` to be additionally modified by delegate implementers.
This is useful to plug in a custom snapping logic.

### Infos for Reviewer

The intention was to open up the snapping logic but make it optional and don't change snapping behavior if custom logic is not provided. If custom snapping doesn't provide a valid value (ie. fails), the default snapping shall be used as fallback.

2024-07-17 15:42 UTC, boldtrn commented on MapboxCoreNavigation/RouteController.swift
> +        let snappedDefault = self.rawLocation?.snapped(to: self.routeProgress.currentLegProgress)
Aren't you doing duplicated work here? If there is a delegate, the delegate should do the snapping, otherwise the default snapping happens.

2024-07-17 15:42 UTC, boldtrn requested changes
Thanks for the nice PR, I think this will be helpful in using the library. Could you double check that we don't have to snap the location twice?

2024-07-18 14:05 UTC, boldtrn approved these changes
LGTM 👍 - could you add a changelog entry for your changes?

2024-07-18 15:28 UTC, sotomski commented
Sure thing 👍

2024-07-18 15:38 UTC, merged